---
apiVersion: v1
kind: Namespace
metadata:
 name: psait-ns
---
apiVersion: v1
kind: Pod
metadata:
 name: testpod
 namespace: psait-ns
 labels:
  app: demoapp
spec:
 containers:
 - name: webappcontainer
   image: psait/pankajsiracademy:latest
   ports:
   - containerPort: 9090
---   
apiVersion: v1
kind: Service
metadata:
 name: test-service
 namespace: psait-ns
spec:
 type: NodePort
 selector:
  app: demoapp
 ports:
  - port: 80
    targetPort: 9090
    nodePort: 30070
...