---
apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    app: demoapp
spec:
  containers:
    - name: test
      image: psait/pankajsiracademy:latest
      ports:
        - containerPort: 9090
...
